version: '3.8'

services:
  almaal-frontend:
    image: almaal-frontend:v1
    build:
      context: ./front-end
      dockerfile: Dockerfile.frontend
    container_name: almaal_frontend
    ports:
      - 3000:3000

  almaal-backend:
    image: almaal-server:v1
    build:
      context: ./back-end
      dockerfile: Dockerfile.backend
    container_name: almaal_server
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_PORT=3001
      - DB_USER=team-almaal
      - DB_PASSWORD=team-almaal123
      - DB_URL=mongodb+srv://team-almaal:team-almaal123@cluster0.euf8pot.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 3001:3001
    pull_policy: never
