name: Docker Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into droplet
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          pwd
          cd final-project-team-almaal
          git pull
          # docker-compose down
          # # docker system prune -a
          # # docker stop $(docker ps -a -q)
          # # docker rm almaal-server:v1
          # # docker rm almaal-frontend:v1
          # # docker rmi almaal-server:v1
          # # docker rmi almaal-frontend:v1
          # docker-compose up -d