name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker images using docker-compose
    #   run: docker-compose up
    - name: Install back-end dependencies
      run: |
        cd back-end
        npm install
    - name: Run npm test in back-end directory
      run: |
        echo "Running tests"
        cd back-end
        npm test
